tci:
  host: localhost
  port: 40001
  trx_number: 0
  auto_reconnect: true
  reconnect_delay: 3.0
  force_ptt: true
  keepalive_ping: false
operator:
  callsign: SM0ONR
cw:
  default_mode: CW
  speed_wpm: 25
  keyer_mode: iambic-b
  tx_settle_time: 0.05
sidetone:
  enabled: true
  frequency: 510
  volume: 0.28440366972477066
usb_hid:
  enabled: true
  device_path: null
  vendor_id: '2886'
  product_id: 802f
  debug: false
  auto_reconnect: true
vail_adapter:
  enabled: true
  keyer_mode: 8
  speed_wpm: 25
  sidetone_note: 72
  output_mode: keyboard
  allow_dynamic_speed: true
function_keys:
  F1: '{callsign}'
  F2: 5nn
  F3: CQ CQ CQ DE {callsign} {callsign} K
  F4: TU 73 DE {callsign}
  F5: QRZ?
  F6: PSE QRS
  F7: QRL?
  F8: TEST V V DE {callsign}
  F9: TEST
  F10: ''
  F11: tnx ur 559 559 bk
  F12: ''
